### ISSUE TITLE
Create basic structure for new dashboard version

### ISSUE THREAD

**Issue by knightus** [mobile-health/doctor-dashboard-v2#1]
## Todos:
Currently, this version will be built by `reactJS` as one of main technologies:
- [ ] Add basic skeleton with must-have libraries
- [ ] Setting up build tools:
  - [ ] `webpack`
  - [ ] `gulp` (For some vendor libs that are not compatible with `webpack`)
- [ ] Implement `JWT` authentication
- [ ] Add basic routes & views
  - [ ] Sign in
  - [ ] Sign up
  - [ ] Profile
- [ ] Write a great `README.md`

## Topics that need to research
- `isomorphic rendering`: especially in pairing with `Go`
- `JWT`: Deeper understanding about the whole system
- `testing in React.js`: Ways to write better & faster test suites.
